FROM golang:latest
MAINTAINER andrewpqc <3480437308@qq.com>

ENV DEPLOY_PATH /xueer-promotion
ENV REDIS_ADDR <you redis address>
ENV X_API_KEY <your X_API_KEY>
RUN mkdir -p $DEPLOY_PATH
WORKDIR $DEPLOY_PATH

Add muxi-promotion-service muxi-promotion-service
CMD ./muxi-promotion-service

